    // Este archivo centraliza TODOS los iconos de la app.

import {
  User,
  Mail,
  Lock,
  Calendar,
  Clock,
  LogIn,
  LogOut,
  Store,
  Scissors,
  Phone,
  Settings,
  ChevronLeft,
  ChevronRight,
  Plus,
  Check,
  X,
  Loader2,
  Eye,
  EyeClosed,
  Edit,
  Trash ,
  SquareArrowLeft,
  Heart 
} from "lucide-react";

export const Icons = {
  user: User,
  mail: Mail,
  lock: Lock,
  calendar: Calendar,
  clock: Clock,
  login: LogIn,
  logout: LogOut,
  store: Store,
  scissors: Scissors,
  phone: Phone,
  settings: Settings,
  left: ChevronLeft,
  right: ChevronRight,
  plus: Plus,
  check: Check,
  close: X,
  spinner: Loader2,
  eye: Eye,
  eyeClosed: EyeClosed,
  edit: Edit,
  trash: Trash,
  squareArrowLeft: SquareArrowLeft,
  heart: Heart
};
